/**
 * DeckWing Design System — DO NOT EDIT THIS FILE
 *
 * This file imports the JSON data files and exports them for the app.
 * To change design values, edit the .json files in this directory.
 *
 * Contributors: edit the JSON files, not this file.
 */

import colors from './colors.json';
import typography from './typography.json';
import borders from './borders.json';
import spacingData from './spacing.json';
import shadowsData from './shadows.json';
import icons from './icons.json';
import images from './images.json';
import chartsData from './charts.json';
import researchSourcesData from './research-sources.json';
import interviewQuestionsData from './interview-questions.json';

// Colors
export const palette = colors;

// Typography
export const fonts = typography.fonts;
export const slideFontSizes = typography.slideFontSizes;
export const uiFontSizes = typography.uiFontSizes;

// Borders
export const borderRadius = borders.borderRadius;
export const borderWidth = borders.borderWidth;
export const borderOpacity = borders.borderOpacity;

// Spacing
export const spacing = spacingData.spacing;
export const slideSpacing = spacingData.slideSpacing;
export const panelWidths = spacingData.panelWidths;

// Shadows
export const shadows = shadowsData.shadows;
export const glows = shadowsData.glows;

// Icons
export const slideIcons = icons.slideIcons;
export const allIcons = Object.values(icons.slideIcons).flat();
export const iconSizes = icons.iconSizes;

// Images
export const logos = images.logos;
export const logoSettings = images.logoSettings;

// Charts
export const charts = chartsData;

// Research
export const researchSources = researchSourcesData;

// Interview
export const interviewQuestions = interviewQuestionsData;
